name: Check workflow

on:
  push:
  pull_request:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # a single job called "check"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8","3,9","3.10"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: initial checkout
        uses: actions/checkout@v3
        # fetch all history for all branches and tags
        with:
          fetch-depth: 0
      - name: setup initial Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
        continue-on-error: true
      - name: install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install --trusted-host pypi.org setuptools wheel
      - name: Build
        run: |
          python setup.py check --metadata
          python setup.py sdist bdist_wheel
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello there ${{ github.event.inputs.name }} !"
