name: Check workflow

on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # a single job called "check"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: initial checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup initial Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: install build
        run: python -m pip install build
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
